name: Build and Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - master  # master 브랜치에 푸시될 때마다 실행됩니다.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Ruby 버전을 명시합니다.
          bundler-cache: true # Bundler 의존성을 캐시하여 빌드 속도를 높입니다.
          cache-version: 1

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        # Jekyll을 사용하여 사이트를 빌드하고, 결과물을 `_site` 폴더에 저장합니다.
        # JEKYLL_ENV=production 환경 변수는 프로덕션용으로 빌드하도록 합니다.
        run: bundle exec jekyll build --source . --destination ./_site
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        # 빌드 결과물을 GitHub Pages에 배포할 수 있도록 업로드합니다.
        uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4